import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './styles/globals.scss';
import NavBarContent from './Components/Organisms/NavBarContent';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
        <body className={inter.className}>
          <div style={{ backgroundColor: '#0298DB', padding: '80px' }} />
                <NavBarContent />
                {children}
            </body>
        </html>
    );
}
