import type { Metadata } from 'next';
import './styles/globals.scss';
import styles from '../app/Components/Views/HomePage/HomePage.module.scss';
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body>
                <div >{children}</div>
            </body>
        </html>
    );
}
