import type { Metadata } from 'next';
import './styles/globals.scss';
import NavBarContent from './Components/Organisms/NavBarContent';
import styles from './Components/Views/HomPageContent.module.scss';
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body>
                <div style={{ backgroundColor: '#0298DB', padding: '80px' }} />
                <NavBarContent />
                <div className={styles['center__container']}>{children}</div>
            </body>
        </html>
    );
}
